# Generated by Django 5.1.1 on 2024-09-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.DurationField(),
        ),
    ]
