# Generated by Django 5.1.1 on 2024-09-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='via',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
