# Generated by Django 5.1.1 on 2024-09-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_schedule_via'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
