# Generated by Django 5.1.1 on 2024-09-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_alter_route_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='name',
        ),
    ]
