# Generated by Django 5.1.1 on 2024-09-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_remove_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
